<?php

return [
    'content' => [
        'seo_title' => 'Build Better Health & Side Income in UAE | FreedomWithDXN',
        'meta_description' => 'Join a globally trusted wellness opportunity in the UAE. Free training, flexible part-time start, Halal-certified products. Get your free overview now.',
        'hero_trust' => 'Trusted by 22M+ members in 180+ countries',
        'hero_title' => 'Build Real Freedom from Anywhere in the World - Health, Income & the DXN Opportunity',
        'hero_subtitle' => 'Join a Globally Trusted Wellness Brand - Get a Proven Training System, a Personal Mentor, and a Flexible Income Opportunity Built for Everywhere in the World',
        'primary_cta_text' => 'Watch free overview',
        'reassurance' => '2-minute qualifier - No spam - Free to start',
        'overview_card_title' => 'Free 15-minute overview',
        'overview_card_text' => 'See the products, the business model, and the training path before you decide.',
        'overview_title' => 'Your Freedom Is One Video Away',
        'overview_description' => 'A short overview that shows what DXN is, how the opportunity works, and how you can start without pressure.',
        'video_poster' => 'images/free-overview-poster.png',
        'video_source' => 'Video/free-overview.mp4',
        'gift_kicker' => 'Your special gift box',
        'gift_title' => "The Offer You'll Love After Watching This Video!",
        'gift_description' => 'Everything is prepared to help you understand the opportunity clearly before you decide.',
        'gift_cta_text' => 'Claim free support',
        'qualifier_eyebrow' => 'Free qualifier',
        'qualifier_title' => 'Find your best next step',
        'qualifier_description' => 'Answer 5 quick questions and get matched with the right overview and follow-up.',
        'whatsapp_url' => 'https://wa.me/971555574958',
        'whatsapp_message' => "Hi! I'm interested in the DXN Business Opportunity.",
    ],
    'form' => [
        'step_one_title' => 'What interests you most?',
        'step_one_subtitle' => 'Pick the one that matches you best.',
        'interest_health_label' => 'Better health',
        'interest_income_label' => 'Extra income',
        'interest_both_label' => 'Both - health and income',
        'step_four_title' => 'How soon would you like to take the next step?',
        'step_four_subtitle' => 'This helps us follow up at the right time.',
        'learn_yes_label' => 'I want guidance today',
        'learn_maybe_label' => 'This week is good for me',
        'learn_no_label' => "I'm just exploring for now",
        'contact_title' => 'Get free access',
        'contact_subtitle' => 'Overview video + WhatsApp welcome in 60 seconds.',
        'name_label' => 'Full name',
        'name_placeholder' => 'Your full name',
        'email_label' => 'Email',
        'email_placeholder' => 'you@example.com',
        'whatsapp_label' => 'WhatsApp Number',
        'country_search_placeholder' => 'Search country or code',
        'country_empty_text' => 'No countries found.',
        'phone_placeholder' => 'Phone number',
        'phone_help' => 'Choose your country code, then enter your WhatsApp number.',
        'validation_error' => 'Please complete your name, email, and WhatsApp number.',
        'submit_text' => 'Get free access',
        'privacy_text' => 'Your information is private. Unsubscribe anytime.',
        'success_title' => 'Thank you.',
        'success_message' => 'Your submission has been received. We will send your free overview shortly.',
        'success_badge' => 'Nurture sequence started',
    ],
];
